server:
  servlet:
    context-path: "/api"
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://120.79.61.78:3316/study-test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: detect

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.mystudy.lx.entity

logging:
  level:
    com.kundy.excelutils: debug