server:
  port: 9991
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/micro_eureka
spring:
  main:
    allow-bean-definition-overriding: true
